//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSmartMeter_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationData
    {
        public long id { get; set; }
        public string serialNo { get; set; }
        public string vm { get; set; }
        public string rssi { get; set; }
        public string timestamp { get; set; }
        public string normalized { get; set; }
        public string Batterylifetime { get; set; }
        public string Consumption { get; set; }
    }
}
