//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSmartMeter_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public long id { get; set; }
        public string api_id { get; set; }
        public string serialNo { get; set; }
        public string serialToSain { get; set; }
        public string manufacturer { get; set; }
        public string version { get; set; }
        public string deviceKey { get; set; }
        public string lifecycle { get; set; }
        public string inactive { get; set; }
        public string timezone { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string groups { get; set; }
        public string manual { get; set; }
        public string medium { get; set; }
        public string firstName { get; set; }
        public string address { get; set; }
        public string installDate { get; set; }
        public string metertype { get; set; }
        public string sitecode { get; set; }
        public string vendor { get; set; }
        public string metersize { get; set; }
        public string model { get; set; }
        public string signalstrength { get; set; }
        public string meterstatus { get; set; }
        public Nullable<System.DateTime> import_date { get; set; }
    }
}
