//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSmartMeter_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iSmartMeterEntities1 : DbContext
    {
        public iSmartMeterEntities1()
            : base("name=iSmartMeterEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<StationData> StationDatas { get; set; }
        public virtual DbSet<StationRealTime> StationRealTimes { get; set; }
    }
}
